apiVersion: apps/v1
kind: Deployment
metadata:
  name:nxppru
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nxppru
      
template:
    metadata:
      labels:
        app:nxppru
    spec:
      containers:
      - image: okteto/nxppru:jdsign
        name:nxppru

---

apiVersion: v1
kind: Service
metadata:
  name:nxppru
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "jd_sign"
    port: 8080
  selector:
    app: jd_sign
